version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "BubbleSort-DT-Backend"
s3_prefix = "BubbleSort-DT-Backend"
region = "ap-south-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
resolve_s3 = true
